speedlazer/speedlazer

app/scripts/app.js, app/scripts/components/Choreography.js.coffee, app/scripts/components/Enemy.js.coffee, app/scripts/game.js, app/scripts/levelblocks/GameplayDemo.js.coffee, app/scripts/levelblocks/Generic.js.coffee, app/scripts/lib/Level.js.coffee, app/scripts/scenes/City.js.coffee, app/scripts/scenes/GameOver.js.coffee, app/scripts/scenes/GameplayDemo.js.coffee, app/scripts/scenes/Intro.js.coffee, bower.json
Give enemies a choreography to follow. The choreography can also be repeated.
Todo: 
- Trigger event during choreography (to fire etc)
=> Enemy paths

app/scripts/components/behaviors/shoot_on_sight.coffee, app/scripts/components/entities/Explosion.coffee, app/scripts/components/entities/Mine.coffee, app/scripts/lazerscripts/stage1.coffee, app/scripts/lazerscripts/stage1/jump_mine.coffee, app/scripts/lazerscripts/stage1/shooter.coffee, app/scripts/lazerscripts/stage1boss.coffee, app/scripts/lib/LazerScript.coffee, app/scripts/lib/script_modules/core.coffee, app/scripts/lib/script_modules/entity.coffee, app/scripts/lib/script_modules/level.coffee, app/scripts/scenery/City.coffee
Goals:
- ~~Enemies shooting back~~
- Enemies shooting rockets
- ~~Explosions that hurt~~
- Populate level 1 with enemies
- Bossfight!
=> Bullets, Rockets and Explosions

app/scripts/components/entities/Explosion.coffee, app/scripts/lazerscripts/stage1.coffee, app/scripts/lib/LazerScript.coffee, app/scripts/lib/script_modules/entity.coffee
New explosions and water splashes. Will be better tweaked in the future.. and there's still one water splash that needs replacement
=> New Particles!

app/scripts/components/ShipSpawnable.coffee, app/scripts/components/generic/Choreography.coffee, app/scripts/components/generic/ColorFade.coffee, app/scripts/components/player/Player.coffee, app/scripts/components/player/PlayerAssignable.coffee, app/scripts/game.js, app/scripts/lazerscripts/stage1.coffee, app/scripts/lazerscripts/stage1/sunrise.coffee, app/scripts/lib/LazerScript.coffee, app/scripts/lib/Level.coffee, app/scripts/lib/script_modules/colors.coffee, app/scripts/lib/script_modules/core.coffee, app/scripts/lib/script_modules/entity.coffee, app/scripts/lib/script_modules/level.coffee, app/scripts/scenes/Game.coffee, app/scripts/scenes/GameOver.coffee, app/scripts/scenes/Intro.coffee
Add support for checkpoints.
* Easy for developers to go to a certain section in the level
* Usage for player needs to be defined (Probably for a 'continue' system)
Todo:
=> Checkpoints

app/index.html, app/scripts/app.js, app/scripts/game.coffee, app/styles/style.css
=> Fix #23 fullscreen screen size

app/scripts/components/player/PlayerControlledShip.coffee, app/scripts/components/weapons/RapidWeaponLaser.coffee
The intent is to make the game play more intense, we start by increasing the amount of fire/damage the player can deal, after that we intensify the enemies accordingly.
=> Rapid fire

app/index.html, app/scripts/components/TextInput.coffee, app/scripts/components/controls/GamepadControls.coffee, app/scripts/components/controls/KeyboardControls.coffee, app/scripts/game.coffee, app/scripts/lazerscripts/stage1.coffee, app/scripts/lazerscripts/stage1/stage1boss.coffee, app/scripts/scenes/GameOver.coffee, app/scripts/scenes/Intro.coffee, app/scripts/scenes/Scores.coffee, bower.json
=> Start on highscore support

app/index.html, app/scripts/components/ScrollWall.coffee, app/scripts/components/StageEnd.coffee, app/scripts/components/behaviors/shoot_on_sight.coffee, app/scripts/components/controls/GamepadControls.coffee, app/scripts/components/controls/KeyboardControls.coffee, app/scripts/components/entities/Mine.coffee, app/scripts/components/entities/Projectile.coffee, app/scripts/components/entities/Sun.coffee, app/scripts/components/generic/Choreography.coffee, app/scripts/components/generic/ColorFade.coffee, app/scripts/components/player/PlayerControlledShip.coffee, app/scripts/components/weapons/Bullet.coffee, app/scripts/components/weapons/MiniRocket.coffee, app/scripts/components/weapons/RapidWeaponLaser.coffee, app/scripts/components/weapons/WeaponRocket.coffee, app/scripts/game.coffee, app/scripts/lib/Dialog.coffee, app/scripts/lib/Level.coffee, app/scripts/scenery/City.coffee, app/scripts/scenes/Game.coffee, app/scripts/scenes/Intro.coffee, app/styles/style.css, bower.json
=> Pausing the game

app/scripts/components/ShipSpawnable.coffee, app/scripts/components/player/PlayerControlledShip.coffee, app/scripts/components/weapons/Bullet.coffee, app/scripts/components/weapons/RapidDiagonalLaser.coffee, app/scripts/lazerscripts/stage1.coffee, app/scripts/lazerscripts/stage1/stage1boss.coffee, app/scripts/lib/script_modules/level.coffee, app/scripts/scenes/Game.coffee
Add diagonal shooting.
Not sure about current execution, in combination with powerups.
Should it be diagonal / or straight? or both?
Should they use a single XP powerup? That the L is dropped once, the D is dropped once and the rest is the 'XP' ? And that after level 4 or something the XP will count towards the diagonals?
Lots of questions still :-)
=> Diagonal shooting

app/scripts/components/ScrollWall.coffee, app/scripts/components/entities/LargeDrone.coffee, app/scripts/components/entities/PowerUp.coffee, app/scripts/components/weapons/RapidDiagonalLaser.coffee, app/scripts/components/weapons/RapidWeaponLaser.coffee, app/scripts/lazerscripts/lunch.coffee, app/scripts/lazerscripts/stage1.coffee, app/scripts/lazerscripts/stage1/camera_crew.coffee, app/scripts/lazerscripts/stage1/crew_shooters.coffee, app/scripts/lazerscripts/stage1/scraper_flyer.coffee, app/scripts/lazerscripts/stage1/shooter.coffee, app/scripts/lazerscripts/stage1/stage1boss.coffee, app/scripts/lazerscripts/stage1/swirler.coffee, app/scripts/lib/Level.coffee, app/scripts/lib/script_modules/core.coffee, app/scripts/lib/script_modules/entity.coffee, app/scripts/lib/script_modules/level.coffee, app/scripts/scenery/City.coffee, app/scripts/scenes/Game.coffee, app/scripts/scenes/Scores.coffee
The part of content to bring the player from the city to underground
TODO:
=> New content

app/scripts/components/Enemy.coffee, app/scripts/components/entities/Drone.coffee, app/scripts/components/entities/Explosion.coffee, app/scripts/components/entities/LargeDrone.coffee, app/scripts/components/generic/Choreography.coffee, app/scripts/components/weapons/RapidDiagonalLaser.coffee, app/scripts/components/weapons/RapidWeaponLaser.coffee, app/scripts/lazerscripts/stage1/crew_shooters.coffee, app/scripts/lazerscripts/stage1/scraper_flyer.coffee, app/scripts/lazerscripts/stage1/shooter.coffee, app/scripts/lazerscripts/stage1/stage1boss.coffee, app/scripts/lazerscripts/stage1/swirler.coffee
Fire more, kill enemies faster, more 'juice' on impact. Still lot to debug, explosions are acting weird atm.
=> Speed up firing

app/scripts/components/behaviors/hideable.coffee, app/scripts/components/player/PlayerControlledShip.coffee, app/scripts/components/shaders/ColorWithEffects.coffee, app/scripts/components/shaders/SpriteWithEffects.coffee, app/scripts/lazerscripts/stage1/scraper_flyer.coffee, app/scripts/lazerscripts/stage1/shooter.coffee, app/scripts/lazerscripts/stage1/stage1boss.coffee, app/scripts/lazerscripts/stage1/swirler.coffee, app/scripts/lazerscripts/test.coffee, app/scripts/lib/script_modules/entity.coffee, app/scripts/lib/script_modules/level.coffee, app/scripts/scenery/City.coffee, app/scripts/scenes/Game.coffee
=> New water splashes

app/scripts/components/generic/Choreography.coffee, app/scripts/lazerscripts/test.coffee, app/scripts/lib/BezierPath.coffee, app/scripts/lib/script_modules/entity.coffee, app/scripts/scenes/Game.coffee
=> Homing missile support

app/scripts/components/ShipSpawnable.coffee, app/scripts/components/entities/Drone.coffee, app/scripts/components/entities/LargeDrone.coffee, app/scripts/components/entities/Mine.coffee, app/scripts/components/entities/PowerUp.coffee, app/scripts/components/entities/Rocket.coffee, app/scripts/components/generic/Choreography.coffee, app/scripts/components/generic/TweenPromise.coffee, app/scripts/components/player/Player.coffee, app/scripts/components/player/PlayerSpaceship.coffee, app/scripts/components/utils/WaterSplashes.coffee, app/scripts/components/utils/hideable.coffee, app/scripts/components/weapons/Bullet.coffee, app/scripts/components/weapons/RapidWeaponLaser.coffee, app/scripts/lazerscripts/stage1.coffee, app/scripts/lazerscripts/stage1/crew_shooters.coffee, app/scripts/lazerscripts/stage1/jump_mine.coffee, app/scripts/lazerscripts/stage1/shooter.coffee, app/scripts/lazerscripts/stage1/stage1boss.coffee, app/scripts/lazerscripts/stage1/swirler.coffee, app/scripts/lib/LazerScript.coffee, app/scripts/lib/Level.coffee, app/scripts/lib/LevelScenery.coffee, app/scripts/lib/script_modules/core.coffee, app/scripts/lib/script_modules/level.coffee, app/scripts/scenery/City.coffee
=> New powerups

app/scripts/components/entities/PlayerClone.coffee, app/scripts/components/generic/Choreography.coffee, app/scripts/components/shaders/SpriteShader.coffee, app/scripts/lazerscripts/stage1.coffee, app/scripts/lazerscripts/stage1/player_clone.coffee, app/scripts/lazerscripts/stage1/scraper_flyer.coffee, app/scripts/lazerscripts/stage1/stage1boss.coffee, app/scripts/lazerscripts/stage1end.coffee, app/scripts/lazerscripts/stage2.coffee, app/scripts/lib/PauseMenu.coffee, app/scripts/lib/script_modules/entity.coffee, app/scripts/lib/script_templates/level.coffee
Updating last part of the current content.
TODO:
=> New powerups -- part 2

app/index.html, app/scripts/components/BigText.coffee, app/scripts/components/StageEnd.coffee, app/scripts/components/TextInput.coffee, app/scripts/lib/PauseMenu.coffee, app/scripts/scenes/GameOver.coffee, app/scripts/scenes/Intro.coffee, app/scripts/scenes/Scores.coffee, bower.json
Need to test with a gamecontroller still
=> Update crafty 0.80

.eslintrc.js, .travis.yml, config/babel.js, config/webpack.common.js, config/webpack.dev.js, config/webpack.prod.js, package.json, src/components/ShipSpawnable.coffee, src/components/entities/PowerUp.coffee, src/components/player/InventoryWeapons.coffee, src/components/player/Player.coffee, src/components/player/PlayerInfo.coffee, src/components/utils/index.js, src/game.coffee, src/index.js, src/lazerscripts/stage1.coffee, yarn.lock
- Adds 'healthb' powerup, giving the player full health again (not used yet)
- Adds 'healthu' powerup, giving the player full health and increasing the max health by 1 (dropped after endstage bossfight instead of extra life)
- Increased points boundery for an extra life, from 10.000 points to 15.000
=> Health powerups

browserslist, config/uglify.js, config/webpack.prod.js, package.json
=> Effort to improve file size

src/components/ScrollWall.coffee, src/components/generic/ViewportRelativeMotion.coffee, src/components/player/PlayerControlledCube.coffee, src/components/player/PlayerSpaceship.coffee, src/lazerscripts/test.coffee, src/lib/Level.coffee, src/lib/script_modules/level.coffee, src/scenery/City.coffee, src/scenes/Intro.coffee
=> Add support for camera panning (vertical only)

src/components/DebugInfo.js, src/game.coffee, src/lazerscripts/benchmark.coffee, src/lib/PauseMenu.coffee, src/scenes/GameOver.coffee, src/scenes/Intro.coffee, src/scenes/Scores.coffee
Initial stats against Crafty 0.8.0
```
start T: 4s RT: 1ms SRT: 4ms (0) FT: 2ms SFT: 5ms (0) E: 84 FPS: 63
scrolling T: 19s RT: 1ms SRT: 4ms (0) FT: 2ms SFT: 10ms (4) E: 92 FPS: 63
recolor T: 56s RT: 2ms SRT: 7ms (3) FT: 1ms SFT: 13ms (48) E: 121 FPS: 63
swirlers T: 71s RT: 2ms SRT: 7ms (18) FT: 2ms SFT: 20ms (87) E: 122 FPS: 63
swirlers shooting T: 76s RT: 5ms SRT: 7ms (24) FT: 3ms SFT: 20ms (110) E: 128 FPS: 63
swirlers shooting skyline T: 95s RT: 2ms SRT: 7ms (26) FT: 3ms SFT: 20ms (169) E: 162 FPS: 63
end T: 109s RT: 4ms SRT: 7ms (26) FT: 4ms SFT: 20ms (224) E: 106 FPS: 63
```
=> Add benchmark script

CHANGELOG.md, config/webpack.common.js, config/webpack.dev.js, config/webpack.prod.js, package.json, src/components/player/PlayerSpaceship.coffee, src/index.html, src/index.js, src/styles/style.css
=> Start a changelog and versioning process

src/lazerscripts/stage1/ship_boss.coffee, src/scenes/Intro.coffee
Changes:
- Entry points for CHANGELOG.md
> Make sure those changes are added to the CHANGELOG.md
Impact: Major/Minor/Patch
- Increase version number in Changelog for 'Upcoming changes' to reflect this impact,
if not already done (relative to latest release)
- Update `package.json` to this version number, suffixed with `-pre`
=> Some changes to the mid boss gane-play.

src/components/controls/AnalogKeyboardControls.coffee
Bugfix: prevent motion when no keys are pressed
=> Make keyboard controls more stable

src/components/Steering.js, src/components/Weapon.js, src/data/compositions/bullets.composition.json, src/data/entities/Weapons.entity.json, src/data/particles/index.js, src/data/weapons/index.js, src/scripts/stage1/enemies/mines.lazer.js
Changes:
- Entry points for CHANGELOG.md
> Make sure those changes are added to the CHANGELOG.md
Impact: Major/Minor/Patch
- Increase version number in Changelog for 'Upcoming changes' to reflect this impact,
if not already done (relative to latest release)
- Update `package.json` to this version number, suffixed with `-pre`
=> Fine tune enemy content

config/webpack.common.js, src/components/WayPointMotion.js, src/components/WebGLParticles.js, src/editor/components/BarChart.js, src/editor/components/BarChart.scss, src/editor/lib/render-crafty.js, src/editor/modules/animations/AnimationPreview.js, src/editor/modules/animations/index.js, src/editor/modules/audio/index.js, src/editor/modules/compositions/CompositionPreview.js, src/editor/modules/compositions/index.js, src/editor/modules/entities/EntityPreview.js, src/editor/modules/entities/index.js, src/editor/modules/game/GamePreview.js, src/editor/modules/game/index.js, src/editor/modules/particles/ParticleEmitterPreview.js, src/editor/modules/particles/index.js, src/editor/modules/paths/FlyPatternPreview.js, src/editor/modules/paths/index.js, src/editor/modules/sceneries/SceneryPreview.js, src/editor/modules/sceneries/index.js, src/editor/modules/spritesheets/index.js, src/editor/modules/weapons/BulletPatternPreview.js, src/editor/modules/weapons/index.js, src/scripts/playerShip.lazer.js
Changes:
- Entry points for CHANGELOG.md
> Make sure those changes are added to the CHANGELOG.md
Impact: Major/Minor/Patch
- Increase version number in Changelog for 'Upcoming changes' to reflect this impact,
if not already done (relative to latest release)
- Update `package.json` to this version number, suffixed with `-pre`
=> Fix amount entities

src/audio/index.js, src/lib/audio.js, src/lib/dsl/state.js, src/scenes/Credits.js, src/scripts/stage1/battleship.lazer.js, src/scripts/stage1/enemies/battleship.lazer.js, src/scripts/stage1/enemies/droneShip.lazer.js, src/scripts/stage1/enemies/drones.lazer.js, src/scripts/stage1/enemies/helicopter.lazer.js, src/scripts/stage1/enemies/mines.lazer.js, src/scripts/stage1/hacked.lazer.js, src/scripts/stage1/intro.lazer.js
=> Scoring points
